services:
  api:
    build:
      context: api
    env_file:
      - .env
    ports:
      - 5000:80
    profiles:
      - dev
      - prod

  database:
    build:
      context: database
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - dev

  ui:
    build:
      context: ui
      dockerfile: Dockerfile
    profiles:
      - prod

  webserver:
    build:
      context: webserver
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    profiles:
      - prod
