services:
  api:
    build:
      context: api
    env_file:
      - default.env
    ports:
      - 5000:80
    depends_on:
      database:
        condition: service_healthy

  database:
    build:
      context: database
    env_file:
      - default.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  ui:
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - 3000:3000
